version: "3.3"
services:

  layer-0:
    image: staranto/layer-0:latest
    networks:
      - demo-net
    deploy:
      replicas: 3

  simple-http:
    image: staranto/simple-http:latest
    networks:
      - demo-net
    ports:
      - "80:8080"
    deploy:
      replicas: 4
      placement:
        constraints: [node.labels.no-http!=1

networks:
  demo-net:
    driver: overlay
    attachable: true
