version: "3"
services:

  layer-0:
    image: staranto/layer-0:latest
    deploy:
      replicas: 3

  simple-http:
    image: staranto/simple-http:latest
    ports:
      - "80:8080"
    deploy:
      replicas: 5
