name: a-core-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - working-directory: ./a-core/hello-demo
    - run: docker build --tag staranto/junk --file Dockerfile.hello .

